apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-capstone-project
  labels:
    app: django-capstone-project
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-capstone-project
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: django-capstone-project
    spec:
      containers:
        - image: angeloobeta/django-capstone-project
          imagePullPolicy: Always
          name: django-capstone-project
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: django-capstone-project
  labels:
    app: django-capstone-project
spec:
  type: LoadBalancer
  selector:
    app: django-capstone-project
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
      protocol: TCP
