apiVersion: v1
kind: Service
metadata:
  name: django-capstone-project
  labels:
    app: django-capstone-project
spec:
  type: LoadBalancer
  selector:
    app: django-capstone-project
  ports:
    - port: 8000
      targetPort: 8000
